export const clerkAppearance = {
  layout: {
    unsafe_disableDevelopmentModeWarnings: true,
  },
  elements: {
    rootBox: "min-h-screen flex items-center justify-center bg-background p-4",
    card: "w-full max-w-md shadow-xl bg-content1 rounded-large border-0",
    headerTitle: "text-2xl font-bold text-foreground text-center",
    headerSubtitle: "text-foreground/70 text-sm mt-1 text-center",
    socialButtonsBlockButton: "border border-default-200 hover:bg-default-100 transition-colors rounded-medium",
    formFieldInput: "bg-default-100 border border-default-200 rounded-medium px-3 py-2 text-sm text-foreground placeholder:text-foreground/50 focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors",
    formButtonPrimary: "w-full bg-primary hover:bg-primary-600 text-primary-foreground font-medium py-2 px-4 rounded-medium transition-colors",
    formFieldLabel: "text-sm font-medium text-foreground",
    dividerLine: "bg-default-200",
    dividerText: "text-foreground/60 text-sm",
    footerActionLink: "text-primary hover:text-primary-600 font-medium transition-colors",
    identityPreviewText: "text-foreground/70",
    formHeaderTitle: "text-2xl font-bold text-foreground",
    formHeaderSubtitle: "text-foreground/70 text-sm",
    alertText: "text-danger text-sm",
    formResendCodeLink: "text-primary hover:text-primary-600 font-medium transition-colors",
    otpCodeFieldInput: "bg-default-100 border border-default-200 rounded-medium text-center text-foreground focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors",
    modalBackdrop: "bg-overlay/50",
    modalContent: "bg-content1 rounded-large",
    formFieldErrorText: "text-danger text-xs mt-1",
    formFieldSuccessText: "text-success text-xs mt-1",
    formFieldWarningText: "text-warning text-xs mt-1",
    breadcrumbsItem: "text-foreground/60",
    breadcrumbsItemCurrent: "text-foreground",
    breadcrumbsDivider: "text-foreground/40",
    profileSectionTitle: "text-foreground font-semibold",
    profileSectionContent: "text-foreground/80",
    badge: "bg-primary text-primary-foreground rounded-small",
    accordionContent: "text-foreground/80",
    accordionTriggerButton: "text-foreground hover:text-primary transition-colors",
  },
  variables: {
    colorPrimary: "#66cc8a", // HeroUI primary
    colorDanger: "#ff5861", // HeroUI danger
    colorSuccess: "#00a96e", // HeroUI success
    colorWarning: "#ffbe00", // HeroUI warning
    colorNeutral: "#b9c9be", // HeroUI default
    colorBackground: "hsl(var(--heroui-background))",
    colorInputBackground: "hsl(var(--heroui-default-100))",
    colorInputText: "hsl(var(--heroui-foreground))",
    colorText: "hsl(var(--heroui-foreground))",
    colorTextSecondary: "hsl(var(--heroui-foreground) / 0.7)",
    borderRadius: "0.75rem", // rounded-medium
    fontFamily: "system-ui, -apple-system, sans-serif",
    fontSize: "0.875rem", // text-sm
    spacingUnit: "1rem",
  }
};

export const clerkLocalization = {
  signIn: {
    start: {
      title: "Entre na sua conta",
      subtitle: "para continuar para {{applicationName}}",
      actionText: "Não tem uma conta?",
      actionLink: "Criar conta",
    },
    password: {
      title: "Entre na sua conta",
      subtitle: "para continuar para {{applicationName}}",
      actionText: "Não tem uma conta?",
      actionLink: "Criar conta",
      formTitle: "Entre na sua conta",
      formSubtitle: "para continuar para {{applicationName}}",
    },
    emailCode: {
      title: "Verifique seu e-mail",
      subtitle: "para continuar para {{applicationName}}",
      formTitle: "Código de verificação",
      formSubtitle: "Digite o código de verificação enviado para seu e-mail",
    },
    phoneCode: {
      title: "Verifique seu telefone",
      subtitle: "para continuar para {{applicationName}}",
      formTitle: "Código de verificação",
      formSubtitle: "Digite o código de verificação enviado para seu telefone",
    },
    forgotPassword: {
      title: "Redefinir sua senha",
      subtitle: "para continuar para {{applicationName}}",
      formTitle: "Redefinir sua senha",
      formSubtitle: "Vamos enviar um link de redefinição para seu e-mail",
    },
  },
  signUp: {
    start: {
      title: "Crie sua conta",
      subtitle: "para continuar para {{applicationName}}",
      actionText: "Já tem uma conta?",
      actionLink: "Entrar",
    },
    emailCode: {
      title: "Verifique seu e-mail",
      subtitle: "para continuar para {{applicationName}}",
      formTitle: "Código de verificação",
      formSubtitle: "Digite o código de verificação enviado para seu e-mail",
    },
    phoneCode: {
      title: "Verifique seu telefone",
      subtitle: "para continuar para {{applicationName}}",
      formTitle: "Código de verificação",
      formSubtitle: "Digite o código de verificação enviado para seu telefone",
    },
    continue: {
      title: "Complete seu perfil",
      subtitle: "para continuar para {{applicationName}}",
      formTitle: "Complete seu perfil",
      formSubtitle: "Preencha as informações restantes",
    },
  },
  formFieldLabel__emailAddress: "E-mail",
  formFieldLabel__password: "Senha",
  formFieldLabel__confirmPassword: "Confirmar senha",
  formFieldLabel__firstName: "Nome",
  formFieldLabel__lastName: "Sobrenome",
  formFieldLabel__phoneNumber: "Telefone",
  formFieldInputPlaceholder__emailAddress: "Digite seu e-mail",
  formFieldInputPlaceholder__password: "Digite sua senha",
  formFieldInputPlaceholder__confirmPassword: "Confirme sua senha",
  formFieldInputPlaceholder__firstName: "Digite seu nome",
  formFieldInputPlaceholder__lastName: "Digite seu sobrenome",
  formFieldInputPlaceholder__phoneNumber: "Digite seu telefone",
  formButtonPrimary: "Continuar",
  footerActionLink__signIn: "Entrar",
  footerActionLink__signUp: "Criar conta",
  dividerText: "ou",
  socialButtonsBlockButton: "Continuar com {{provider|titleize}}",
  forgotPasswordLink: "Esqueceu a senha?",
  backButton: "Voltar",
  footerPageLink__help: "Ajuda",
  footerPageLink__privacy: "Privacidade",
  footerPageLink__terms: "Termos",
  signInEnterPasswordTitle: "Digite sua senha",
  signUpEnterPasswordTitle: "Crie uma senha",
  signInEnterEmailCodeTitle: "Digite o código do e-mail",
  signUpEnterEmailCodeTitle: "Verifique seu e-mail",
  signInEnterPhoneCodeTitle: "Digite o código do telefone",
  signUpEnterPhoneCodeTitle: "Verifique seu telefone",
  forgotPasswordTitle: "Redefinir senha",
  formFieldError__notBlank: "Este campo é obrigatório",
  formFieldError__emailAddress_notValid: "E-mail inválido",
  formFieldError__password_pwned: "Esta senha foi comprometida em vazamentos de dados",
  formFieldError__password_too_short: "A senha deve ter pelo menos {{length}} caracteres",
  formFieldError__confirmPassword_no_match: "As senhas não coincidem",
  unstable__errors: {
    identification_deletion_failed: "Você não pode excluir sua última identificação.",
    phone_number_exists: "Este número de telefone já está sendo usado por outra conta.",
    form_identifier_not_found: "Identificador não encontrado.",
    form_password_pwned: "Esta senha foi encontrada como parte de uma violação e não pode ser usada, tente uma senha diferente.",
    form_username_invalid_length: "O nome de usuário deve ter entre {{minLength}} e {{maxLength}} caracteres.",
    form_username_invalid_character: "O nome de usuário pode conter apenas letras, números, sublinhados e hífens.",
    form_param_format_invalid: "Formato de parâmetro inválido.",
    form_password_length_too_short: "A senha deve ter pelo menos {{minLength}} caracteres.",
    form_param_nil: "Parâmetro não pode estar vazio.",
    form_password_incorrect: "Senha incorreta. Tente novamente.",
    not_allowed_access: "Acesso não permitido.",
    session_exists: "Sessão já existe.",
    signin_email_not_found: "E-mail não encontrado.",
    signin_password_incorrect: "Senha incorreta.",
    too_many_requests: "Muitas tentativas. Tente novamente mais tarde.",
    clerk_js_version_mismatch: "Versão do Clerk.js incompatível.",
  }
};